import pysolr

def escape_query(raw_query):
        """
        Escape single quotes in value. \
        May or may not be worth a damn at the moment.
        """
        return raw_query.replace("'", "\'")
        
def delete_query(query, no_confirm=False):
    if not no_confirm:
        s = solr.search(escape_query(query), **{"rows": "0"})
        are_you_sure = raw_input(
            "Are you sure you want to delete {num_recs} \
            records from Solr? Y/N: ".format(num_recs=s.hits)
        )
        if are_you_sure.lower() == "y":
            solr.delete(q=escape_query(query))
        else:
            pass#log.debug("Abandon ship! Not deleting anything.")
    else:
        solr.delete(q=escape_query(query))

SOLR_USERNAME = "solradmin" #Fill in if applicable
SOLR_PASSWORD = "Search4BadgerGeos!" #Fill in if applicable
SOLR_URL = "http://localhost:8983/solr/geodata-core-development/" #  URL for Solr core. Something like http://localhost:8983/solr/blacklightcore/

solr = pysolr.Solr(SOLR_URL, timeout=10, always_commit=True)
results = solr.search('california')

for result in results:
    print("The title is '{0}'.".format(result['dc_title_s']))
    print("The unique key is '{0}'.".format(result['layer_slug_s']))
    print("The provenance is '{0}'.".format(result['dct_provenance_s']))

query = "layer_slug_s:" + "m_4709059_nw_15_1_20170731_20171128"
solr.delete(q=escape_query(query))
#solr.add([{"geoblacklight_version": "1.0", "dc_identifier_s": "m_4709059_nw_15_1_20170731_20171128", "dc_title_s": "2017 Aerial Image: Rocky Island NW Quarter-Quadrangle", "dc_description_s": "This data set contains imagery from the National Agriculture Imagery Program (NAIP). The NAIP acquires digital ortho imagery during the agricultural growing seasons in the continental U.S.. A primary goal of the NAIP program is to enable availability of ortho imagery within one year of acquisition. The NAIP provides two main products: 1 meter ground sample distance (GSD) ortho imagery rectified to a horizontal accuracy within +/- 5 meters of reference digital ortho quarter quads (DOQQ's) from the National Digital Ortho Program (NDOP) or from the National Agriculture Imagery Program (NAIP); 1 meter or 1/2 meter GSD ortho imagery rectified within +/- 6 meters to true ground. The tiling format of NAIP imagery is based on a 3.75' x 3.75' quarter quadrangle with a 300 pixel buffer on all four sides. The NAIP imagery is formatted to the UTM coordinate system using the North American Datum of 1983 (NAD83). The NAIP imagery may contain as much as 10% cloud cover per tile. This file was generated by compressing NAIP imagery that covers the county extent.", "dc_rights_s": "Public", "dct_provenance_s": "WisconsinView", "dc_format_s": "GeoTIFF", "dc_language_s": "English", "layer_id_s": "", "layer_slug_s": "m_4709059_nw_15_1_20170731_20171128", "layer_geom_type_s": "Raster", "layer_modified_dt": "2017-07-31T00:00:00Z", "dct_isPartOf_sm": ["2017 NAIP Imagery"], "dc_creator_sm": ["USDA Farm Service Agency"], "dc_type_s": "Dataset", "dc_subject_sm": ["Imagery"], "dct_spatial_sm": ["Wisconsin"], "dct_issued_s": "2017-07-31", "dct_temporal_sm": "2017", "solr_geom": "ENVELOPE(-90.750000000000000,-90.687500000000000,47.125000000000000,47.062500000000000)", "solr_year_i": "2017", "dct_references_s": "{\"http://schema.org/downloadUrl\":\"ftp://ftp.ssec.wisc.edu/pub/wisconsinview/NAIP_2017_t/47090/m_4709059_nw_15_1_20170731.tif\",\"http://schema.org/url\":\"ftp://ftp.ssec.wisc.edu/pub/wisconsinview/NAIP_2017_t/47090/m_4709059_nw_15_1_20170731.txt\"}"}])

